name: test
on:
  push:
jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go
      - name: Build
        run: go build -v
      - name: Test
        run: go test -v ./...
